### ISSUE TITLE
Kucoin candle data warning

### ISSUE THREAD

**Issue by xmflsct** [BillGatesIII/Vires-in-Numeris#6]
`freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair xxx/USDT: 'hlc3_volatility_16'` running behind https://github.com/mikekonan/exchange-proxy.

**Comment by BillGatesIII** [comment]
Not sure but guess it has something to do with the use of this proxy so you'll have to ask there?
